//GlobalData.ts

type SourceType = "Withdrawals" | "Deposits" | "WhatsApp";

interface Notification {
  testimony: string;
  source: SourceType;
}

export const notifications: Notification[] = (() => {
  const kenyanTribalNames: string[] = [
    // Kikuyu
    "Kamau",
    "Njoroge",
    "Wanjiku",
    "Mwangi",
    "Njeri",
    "Kariuki",
    "Muthoni",
    "Maina",
    "Wambui",
    "Kimani",
    "Githinji",
    "Nyambura",
    "Kinyanjui",
    "Wangari",
    "Ndungu",
    "Wachira",
    "Mumbi",
    "Irungu",
    "Waithera",
    "Githae",
    // Luhya
    "Wamalwa",
    "Nekesa",
    "Simiyu",
    "Nafula",
    "Juma",
    "Barasa",
    "Were",
    "Nanjala",
    "Situma",
    "Wekesa",
    "Masinde",
    "Namukuru",
    "Wanyonyi",
    "Nasimiyu",
    "Wafula",
    "Mukami",
    "Okwara",
    "Naliaka",
    "Sakwa",
    "Makokha",
    // Kalenjin
    "Kipchoge",
    "Chebet",
    "Kibet",
    "Jepkosgei",
    "Kipruto",
    "Cherono",
    "Koech",
    "Jepchirchir",
    "Kiptoo",
    "Chepkoech",
    "Rotich",
    "Jelimo",
    "Kipkemboi",
    "Chelimo",
    "Langat",
    "Jepkemoi",
    "Bii",
    "Chesang",
    "Korir",
    "Jebet",
    // Luo
    "Omondi",
    "Akinyi",
    "Otieno",
    "Adhiambo",
    "Okoth",
    "Achieng",
    "Onyango",
    "Awino",
    "Ouma",
    "Apiyo",
    "Odhiambo",
    "Anyango",
    "Okello",
    "Atieno",
    "Owuor",
    "Akello",
    "Ochieng",
    "Amondi",
    "Oyoo",
    "Aluoch",
    // Kamba
    "Mutua",
    "Mwende",
    "Musyoka",
    "Nthenya",
    "Kioko",
    "Syombua",
    "Muthama",
    "Wayua",
    "Wambua",
    "Kaluki",
    "Mutisya",
    "Koki",
    "Kyalo",
    "Mwikali",
    "Nzioka",
    "Ndinda",
    "Maingi",
    "Kanini",
    "Munyao",
    "Mbula",
    // Kisii
    "Nyaboke",
    "Mogaka",
    "Kerubo",
    "Onkundi",
    "Moraa",
    "Osoro",
    "Kemunto",
    "Gesare",
    "Nyamweya",
    "Kwamboka",
    "Ondieki",
    "Bosibori",
    "Arasa",
    "Nyanchama",
    "Makori",
    "Bitutu",
    "Ombongi",
    "Nyabonyi",
    "Ogero",
    "Bonareri",
    // Meru
    "Mwenda",
    "Nkatha",
    "Kimathi",
    "Kendi",
    "Murithi",
    "Makena",
    "Muriungi",
    "Kagwiria",
    "Kinoti",
    "Karambu",
    "Marete",
    "Nkirote",
    "Kirimi",
    "Gacheri",
    "Mugambi",
    "Kawira",
    "Mbae",
    "Ntombura",
    "Kobia",
    "Mukiri",
    // Maasai
    "Lenana",
    "Naserian",
    "Senteu",
    "Nashipae",
    "Tipis",
    "Naisiae",
    "Ole Kaelo",
    "Simiren",
    "Parkipuny",
    "Tato",
    "Kuntai",
    "Sialo",
    "Lemayian",
    "Noomali",
    "Saruni",
    "Nampayio",
    "Mpoke",
    "Nenkoitoi",
    "Lekishon",
    "Siyapei",
    // Mijikenda (Giriama, Digo, Duruma, Chonyi, etc.)
    "Kazungu",
    "Mbeyu",
    "Charo",
    "Sidi",
    "Baya",
    "Asha",
    "Kenga",
    "Mwavita",
    "Gona",
    "Fatuma",
    "Tsuma",
    "Mekatilili",
    "Dama",
    "Kahindi",
    "Mwaro",
    "Wanje",
    "Kombo",
    "Ngowa",
    "Mlewa",
    "Safina",
    // Turkana
    "Ekal",
    "Akiru",
    "Lokoru",
    "Asekon",
    "Lomurkai",
    "Apua",
    "Ekiru",
    "Atabo",
    "Loter",
    "Akuwam",
    "Napeyok",
    "Eyanae",
    "Lokidor",
    "Angeline",
    "Samal",
    "Abok",
    "Ichumar",
    "Amoit",
    "Lomelo",
    "Areng",
    // Embu / Mbeere
    "Njue",
    "Wawira",
    "Njeru",
    "Muthoni",
    "Mbogo",
    "Gicuku",
    "Kariuki",
    "Ngima",
    "Nyaga",
    "Runji",
    // Taita / Taveta
    "Mwatela",
    "Wakesho",
    "Mwachofi",
    "Mkanjala",
    "Mghoi",
    "Dawida",
    "Sarai",
    "Mcharo",
    "Sera",
    "Mshimba",
    // Somali-Kenyan / Borana / Gabra / Rendille (often Muslim names, shared across communities)
    "Abdi",
    "Fatuma",
    "Hassan",
    "Halima",
    "Ali",
    "Asha",
    "Mohamed",
    "Amina",
    "Omar",
    "Zainab",
    "Ibrahim",
    "Khadija",
    "Ahmed",
    "Mariam",
    "Yusuf",
    "Farhiya",
    "Hussein",
    "Safia",
    "Said",
    "Hawa",
    "Abdullahi",
    "Rahma",
    "Osman",
    "Yasmin",
    "Jibril",
    "Nimo",
    "Mahat",
    "Fartun",
    "Ismail",
    "Shukri",
    // Rendille / Samburu (can overlap with Maasai or have unique ones)
    "Lelekwe",
    "Napanu",
    "Lekuton",
    "Ltumbesi",
    "Leripe",
    "Nalotu",
    "Lparmelo",
    "Ntinyari",
    "Losike",
    "Seina",
  ];

  const globalNames: string[] = [
    "Mike",
    "Carol",
    "David",
    "Sarah",
    "John",
    "Linda",
    "Robert",
    "Patricia",
    "Michael",
    "Jennifer",
    "William",
    "Mary",
    "James",
    "Susan",
    "Joseph",
    "Margaret",
    "Charles",
    "Dorothy",
    "Thomas",
    "Lisa",
    "Daniel",
    "Nancy",
    "Paul",
    "Karen",
    "Mark",
    "Betty",
    "George",
    "Helen",
    "Steven",
    "Sandra",
    "Edward",
    "Donna",
    "Brian",
    "Carolyn",
    "Ronald",
    "Ruth",
    "Anthony",
    "Sharon",
    "Kevin",
    "Michelle",
    "Jason",
    "Laura",
    "Matthew",
    "Sarah",
    "Gary",
    "Kimberly",
    "Timothy",
    "Deborah",
    "Jose",
    "Jessica",
    "Larry",
    "Shirley",
    "Jeffrey",
    "Cynthia",
    "Frank",
    "Angela",
    "Scott",
    "Melissa",
    "Eric",
    "Brenda",
    "Stephen",
    "Amy",
    "Andrew",
    "Anna",
    "Raymond",
    "Rebecca",
    "Gregory",
    "Virginia",
    "Joshua",
    "Kathleen",
    "Jerry",
    "Pamela",
    "Dennis",
    "Martha",
    "Walter",
    "Debra",
    "Patrick",
    "Barbara",
    "Peter",
    "Christine",
    "Harold",
    "Marie",
    "Douglas",
    "Janet",
    "Henry",
    "Catherine",
    "Carl",
    "Frances",
    "Arthur",
    "Ann",
    "Ryan",
    "Joyce",
    "Roger",
    "Diane",
    "Joe",
    "Alice",
    "Juan",
    "Julie",
    "Jack",
    "Heather",
    "Albert",
    "Teresa",
    "Jonathan",
    "Doris",
    "Justin",
    "Gloria",
    "Terry",
    "Evelyn",
    "Gerald",
    "Jean",
    "Keith",
    "Cheryl",
    "Samuel",
    "Mildred",
    "Willie",
    "Katherine",
    "Lawrence",
    "Joan",
    "Noah",
    "Ashley",
    "Liam",
    "Olivia",
    "Jackson",
    "Emma",
    "Aiden",
    "Ava",
    "Lucas",
    "Sophia",
    "Ethan",
    "Isabella",
    "Mohammed",
    "Fatima",
    "Ahmed",
    "Aisha",
    "Ali",
    "Khadija",
    "Omar",
    "Zainab",
    "Yusuf",
    "Maryam",
    "Chen",
    "Li",
    "Wang",
    "Zhang",
    "Liu",
    "Devi",
    "Singh",
    "Kumar",
    "Patel",
    "Shah",
    "Silva",
    "Santos",
    "Ferreira",
    "Pereira",
    "Oliveira",
    "Kim",
    "Lee",
    "Park",
    "Choi",
    "Jeong",
    "Tanaka",
    "Suzuki",
    "Sato",
    "Takahashi",
    "Watanabe",
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Garcia",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Perez",
    "Sanchez",
    "Ramirez",
    "Flores",
    "Nguyen",
    "Tran",
    "Le",
    "Pham",
    "Hoang",
    "Ivanov",
    "Smirnov",
    "Kuznetsov",
    "Popov",
    "Vasilyev",
    "Anastasia",
    "Dimitri",
    "Elena",
    "Nikolai",
    "Svetlana",
    "Olga",
    "Vladimir",
    "Tatiana",
    "Sergei",
    "Irina",
    "Priya",
    "Ananya",
    "Rohan",
    "Aditya",
    "Sneha",
    "Vikram",
    "Pooja",
    "Arjun",
    "Neha",
    "Rahul",
    "Kenji",
    "Yuki",
    "Haruto",
    "Aoi",
    "Sakura",
    "Hiroshi",
    "Hana",
    "Ren",
    "Mei",
    "Daiki",
    "Sofia",
    "Mateo",
    "Valentina",
    "Santiago",
    "Camila",
    "Sebastian",
    "Isabella",
    "Matias",
    "Valeria",
    "Diego",
    "Chinedu",
    "Adebayo",
    "Ngozi",
    "Emeka",
    "Funmilayo",
    "Kwame",
    "Afi",
    "Babatunde",
    "Yetunde",
    "Kofi",
  ];

  const sources: SourceType[] = ["Withdrawals", "Deposits", "WhatsApp"];
  const generatedNotifications: Notification[] = [];
  const usedAmounts = new Set<number>(); // Ensures unique amounts

  const targetKenyanNames = 400;
  const totalNotifications = 700;

  const usernames: string[] = [];

  // Populate Kenyan names
  for (let i = 0; i < targetKenyanNames; i++) {
    let name =
      kenyanTribalNames[Math.floor(Math.random() * kenyanTribalNames.length)];
    if (Math.random() < 0.1 && usernames.length > 100) {
      // Add variety for potentially repeated base names
      name += Math.floor(Math.random() * 90) + 10;
    } else if (Math.random() < 0.05 && usernames.length > 50) {
      name += String.fromCharCode(65 + Math.floor(Math.random() * 26));
    }
    usernames.push(name);
  }

  // Populate remaining with global names
  const remainingGlobalNames = totalNotifications - targetKenyanNames;
  for (let i = 0; i < remainingGlobalNames; i++) {
    let name = globalNames[Math.floor(Math.random() * globalNames.length)];
    if (Math.random() < 0.1 && i > remainingGlobalNames * 0.2) {
      // Add variety for potentially repeated base names
      name += Math.floor(Math.random() * 90) + 10;
    }
    usernames.push(name);
  }

  // Shuffle the combined usernames list
  for (let i = usernames.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [usernames[i], usernames[j]] = [usernames[j], usernames[i]];
  }

  for (let i = 0; i < totalNotifications; i++) {
    const username: string = usernames[i]; // Use the pre-shuffled mixed list
    const source: SourceType =
      sources[Math.floor(Math.random() * sources.length)];

    let amount: number;
    do {
      amount = Math.floor(Math.random() * (169382 - 361 + 1)) + 361;
    } while (usedAmounts.has(amount)); // Ensure amount is unique
    usedAmounts.add(amount);

    let testimony = "";
    const formattedAmount: string = amount.toLocaleString(); // Add commas for readability

    if (source === "WhatsApp") {
      testimony = `${username} has just earned KES${formattedAmount} from WhatsApp`;
    } else if (source === "Withdrawals") {
      testimony = `${username} has just withdrawn KES${formattedAmount}.`;
    } else if (source === "Deposits") {
      testimony = `${username} has just deposited Ksh ${formattedAmount}.`;
    }

    generatedNotifications.push({
      testimony: testimony,
      source: source,
    });
  }

  // Final shuffle of the notifications themselves
  for (let i = generatedNotifications.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [generatedNotifications[i], generatedNotifications[j]] = [
      generatedNotifications[j],
      generatedNotifications[i],
    ];
  }

  return generatedNotifications;
})();

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Deps",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Rep)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland (Republic)",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
