//GlobalData.ts

export const notifications = [
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "CK3 has just withdrawn KES2300",
    source: "Withdrawals",
  },
  {
    testimony: "Mike has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Betty has just earned KES500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Clinton Otieno has just earned KES6720 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Josh Mwangi has just earned KES8900 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Wambui Ann has just earned KES1200from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Musyoka has just earned KES6210 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Winne has just earned KES78030 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Marie has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Njuguna has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "ChrisPaul has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Carol has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Peter Nekesa has just earned KES4500 from Whatsapp",
    source: "Whatsapp",
  },
  {
    testimony: "Wainani has just earned KES4500 from Whatsapp",
    source: "Withdrawals",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Deps",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Rep)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland (Republic)",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
